# Generated by Django 5.2.9 on 2025-12-06 21:50

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['-data_de_ingresso'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nome'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['-data_de_matricula'], 'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(db_index=True, max_length=11, unique=True, validators=[core.models.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_de_ingresso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], db_index=True, default='ativo', max_length=10),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], db_index=True, default='pendente', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'curso')},
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['nome', '-data_de_ingresso'], name='core_aluno_nome_f06c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['status', 'nome'], name='core_curso_status_cb62b8_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['aluno', 'status'], name='core_matric_aluno_i_c95ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['curso', 'status'], name='core_matric_curso_i_96c963_idx'),
        ),
    ]
